Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class GalleryController : Controller
    {
        private readonly ILogger<GalleryController> _logger;

        public GalleryController(ILogger<GalleryController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class OffersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OffersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Offers
        public async Task<IActionResult> Index()
        {
              return View(await _context.Offer.ToListAsync());
        }

        // GET: Offers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .FirstOrDefaultAsync(m => m.ID == id);
            if (offer == null)
            {
                return NotFound();
            }
            return NotFound();
        }

        // GET: Offers/Create
        public IActionResult Create()
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));

            return View();
        }

        // POST: Offers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Description,Img_url,Price")] Offer offer)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (ModelState.IsValid)
            {
                _context.Add(offer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(offer);
        }

        // GET: Offers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer.FindAsync(id);
            if (offer == null)
            {
                return NotFound();
            }
                return View(offer);

        }

        // POST: Offers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Description,Img_url,Price")] Offer offer)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (id != offer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(offer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(offer);
        }

        // GET: Offers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .FirstOrDefaultAsync(m => m.ID == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // POST: Offers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (_context.Offer == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Offer'  is null.");
            }
            var offer = await _context.Offer.FindAsync(id);
            if (offer != null)
            {
                _context.Offer.Remove(offer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfferExists(int id)
        {
          return _context.Offer.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" type="image/png" href="https://i.imgur.com/ZTBL0vk.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MJM Holidays - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 navbar-body">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://s3-alpha-sig.figma.com/img/8061/a38b/efae0f0d30a21df520e3ec19ce1b6425?Expires=1673827200&Signature=p~DzMj4FPtNtdELIqkasEhuXtcn5S~O1xbUu3ldyBJXofg1TXsLoUXTTVYoNOxd2kuOENBGERp2VFYwpnIsAqY-8KmpUlKp1ayWH2Ltkb3UfY-r3xt5BfqRNiXR4dHjvwAiimzDznHtLdBzmcgzddWpCDnOMNC5EJIuTiQ9K7TLN9d6gpG2eJxP-Z-033ZgsGx4eAlXJJmmG2b1LQ9bapGo-U31wy6fgSViWXiP79pNGJoZ5zjicMB5sNErcjFIM00BO3cHBJu7jJ9rraKWhduP37KKLBiw~gRiAulKQTAiCHU7HAjEuSth9mlr9YaHl2Y2r~8hfkGb8NSsZ2eA7iQ__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4 " class="img img-fluid logo" width="80px" alt= "MJM Holidays" /> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Home" asp-action="Index"><b>Strona główna</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Offers" asp-action="Index">Oferta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Galeria</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="mt-5 p-2">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center">
                            <img src="https://s3-alpha-sig.figma.com/img/8061/a38b/efae0f0d30a21df520e3ec19ce1b6425?Expires=1673827200&Signature=p~DzMj4FPtNtdELIqkasEhuXtcn5S~O1xbUu3ldyBJXofg1TXsLoUXTTVYoNOxd2kuOENBGERp2VFYwpnIsAqY-8KmpUlKp1ayWH2Ltkb3UfY-r3xt5BfqRNiXR4dHjvwAiimzDznHtLdBzmcgzddWpCDnOMNC5EJIuTiQ9K7TLN9d6gpG2eJxP-Z-033ZgsGx4eAlXJJmmG2b1LQ9bapGo-U31wy6fgSViWXiP79pNGJoZ5zjicMB5sNErcjFIM00BO3cHBJu7jJ9rraKWhduP37KKLBiw~gRiAulKQTAiCHU7HAjEuSth9mlr9YaHl2Y2r~8hfkGb8NSsZ2eA7iQ__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4 " class="img img-fluid logo" width="150px" alt= "MJM Holidays" />
                </div>
                <div class="col-md-6 text-left d-table">
                    <span class="d-table-cell align-middle">Jesteś ostatnio przemęczony i nie możesz się skupić na pracy, a aura za oknem sprawia, że najchętniej przez cały dzień nie wychodziłbyś spod kołdry? Sprawdź jaką ofertę przygotowało nasze biuro podróży!</span>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>