Models/Offer.cs
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    public class Offer
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Img_url { get; set; }
        public decimal Price { get; set; }


        public Offer()
        {

        }
    }

}

Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class OffersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OffersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Offers
        public async Task<IActionResult> Index()
        {
              return View(await _context.Offer.ToListAsync());
        }

        // GET: Offers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .FirstOrDefaultAsync(m => m.ID == id);
            if (offer == null)
            {
                return NotFound();
            }
            return NotFound();
        }

        // GET: Offers/Create
        public IActionResult Create()
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));

            return View();
        }

        // POST: Offers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Description,Img_url,Price")] Offer offer)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (ModelState.IsValid)
            {
                _context.Add(offer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(offer);
        }

        // GET: Offers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer.FindAsync(id);
            if (offer == null)
            {
                return NotFound();
            }
                return View(offer);

        }

        // POST: Offers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Description,Img_url,Price")] Offer offer)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (id != offer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(offer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(offer);
        }

        // GET: Offers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .FirstOrDefaultAsync(m => m.ID == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // POST: Offers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (User.Identity.Name != "Admin@admin.pl")
                return RedirectToAction(nameof(Index));
            if (_context.Offer == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Offer'  is null.");
            }
            var offer = await _context.Offer.FindAsync(id);
            if (offer != null)
            {
                _context.Offer.Remove(offer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfferExists(int id)
        {
          return _context.Offer.Any(e => e.ID == id);
        }
    }
}

Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using ASPNetCoreIdentityCustomFields.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Data.Migrations;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public ReservationsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Reservations
        public async Task<IActionResult> Index()
        {

            var user_id = _userManager.GetUserId(User);

                var reservations = from offer in _context.Offer join reservation in _context.Reservation on offer.ID equals reservation.Offer_id where reservation.User_id == user_id select offer;
                return View(reservations);

               
        }



        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,User_id,Offer_id,date")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reservation);
        }






        private bool ReservationExists(int id)
        {
          return _context.Reservation.Any(e => e.ID == id);
        }
    }
}

Views/Offers/Create.cshtml
@model WebApplication2.Models.Offer

@{
    ViewData["Title"] = "Create";
}

<h1>Dodaj nową ofertę wakacji</h1>

<h4>Poniżej uzupełnij dane, aby poprawnie dodać ofertę wakacji</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img_url" class="control-label"></label>
                <input asp-for="Img_url" class="form-control" />
                <span asp-validation-for="Img_url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wróć do listy</a>
</div>

Views/Offers/Delete.cshtml
@model WebApplication2.Models.Offer

@{
    ViewData["Title"] = "Delete";
}

<h1>Usuwanie oferty</h1>

<h3>Jesteś pewien, że chcesz usunąć tę ofertę?</h3>
<div>
    <h4>Tego kroku nie można cofnąć!</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Img_url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Img_url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Wróć do listy</a>
    </form>
</div>

Views/Offers/Details.cshtml
@model WebApplication2.Models.Offer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Offer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Img_url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Img_url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Offers/Edit.cshtml
@model WebApplication2.Models.Offer

@{
    ViewData["Title"] = "Edit";
}
<h1>Edytuj ofertę wakacji</h1>

<h4>Poniżej są podane opcje, które możesz zmienić w tej ofercie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img_url" class="control-label"></label>
                <input asp-for="Img_url" class="form-control" />
                <span asp-validation-for="Img_url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wróć do listy ofert</a>
</div>

Views/Offers/Index.cshtml
@model IEnumerable<WebApplication2.Models.Offer>
@using ASPNetCoreIdentityCustomFields.Data;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@{
    ViewData["Title"] = "Oferty";
}
@if (User.Identity.Name == "Admin@admin.pl")
{
    <a asp-controller="Offers" asp-action="Create">Dodaj ofertę wakacji</a>
}
        <div class="container mt-5 text-center">
    <h1 class="display-2"><b>Aktualne oferty wakacji</b></h1>
    <h3>Zarezerwuj najlepsze wakacje swojego życia z MJM Holidays</h3>
@foreach (var item in Model) {
    <div class="row">
        <div class="col-md-12 row offer mt-5">

            <div class="offer-left col-4">
                    <img src="@Html.DisplayFor(modelItem => item.Img_url)" class="img-fluid w-100">
            </div>

            <div class="offer-right col-8">
                <div class="offer-title">
                        <h2>@Html.DisplayFor(modelItem => item.Title)</h2>
                </div>
                <div class="offer-description">
                        <p>@Html.DisplayFor(modelItem => item.Description)</p>
                <div class="offer-footer text-center mt-5">
                    @if (SignInManager.IsSignedIn(User))
                            {
                                @using (Html.BeginForm("create", "Reservations", FormMethod.Post))
                                {
                                    <input type="hidden" name="offer_id" value="@Html.DisplayFor(modelItem => item.ID)">
                                    <input type="hidden" name="User_id" value="@UserManager.GetUserId(User)">
                                    <input type="date" name="date" required/>
                                    <button class="btn-lg btn-outline-success">Zarerezerwuj za @Html.DisplayFor(modelItem => item.Price) zł</button>
                                }
                            } else
                            {
                                <button class="btn-lg btn-outline-success">Zaloguj się aby zarezerwować! za @Html.DisplayFor(modelItem => item.Price) zł</button>
                            }
                            @if (User.Identity.Name == "Admin@admin.pl")
                            {
                                <a asp-action="Edit" asp-route-id="@item.ID">Edytuj</a>
                                <a asp-action="Delete" asp-route-id="@item.ID">Usuń</a>
                            }
                        </div>
                </div>
            </div>
                

        </div>


    </div>
}
        </div>